### ISSUE TITLE
Allow import CFN template for a given resource

### ISSUE THREAD

**Issue by JohnPreston** [compose-x/ecs_composex#159]
I already have a CFN template for a specific type of resource and all I want is to deploy it along with the stacks defined in composex.
ComposeX should only modify the template to add outputs to allow access and such but nothing else.
```
x-sqs:
  queueA:
    TemplatePath: ./path_to_template.yml
    TemplateParametersPath: ./path_to_params.json
    TemplateConfigPath: ./path_to_config.json
```

**Comment by JohnPreston** [comment]
Might instead allow people to do `x-stacks` allowing them to define locally the template and parameters to ingest.
ComposeX would automatically add tags according to `x-tags`.
Might be the short-term way to allow Lambda deployments from existing CFN templates.

**Comment by JohnPreston** [comment]
So from use-cases, came out to do something more like

```yaml
x-sqs:
  queueA:
    Import:
      TemplatePath: myexisting.template
      LogicalId: TheResourceLogicalIdInTemplate
```
If attributes values are a Cfn Helper (Ref/Sub/else) try to understand the source of it. If from parameter, void to a default value.
If mappings, import mappings too.
