### ISSUE TITLE
[FR| Add support to register x-resources into AWS CloudMap

### ISSUE THREAD

**Issue by JohnPreston** [compose-x/ecs_composex#288]
**Is your feature request related to a problem? Please describe.**
As a developer I am used to define things like databases with short names such as `db` or `dbserver`.
I would like the ability for services which are going to be running in a VPC to be recorded similarly into AWS Private CloudMap

**Describe the solution you'd like**
```
x-rds:
  dbA:
    MacroParameters:
      RegisterInstanceToCloudMap: True|False
```

**Comment by JohnPreston** [comment]
Change syntax

```yaml

dbA:
  Settings:
    Subnets: <>
    x-cloudmap: str # Compose-x default settings for the given x-resource

```

```yaml

dbA:
  Settings:
    Subnets: <>
    x-cloudmap:
      map:
        DnsSettings:
          Hostname: <>
          Port: <>
        AdditionalValues:
          <arbitrary name>: <value>
        ReturnValues
          <CFN Return Value>: <Attribute name in CloudMap>
 
```
