### ISSUE TITLE
AWS::ECS::Service DeploymentConfiguration support via Docker-Compose UPDATE_CONFIG

### ISSUE THREAD

**Issue by JohnPreston** [compose-x/ecs_composex#333]
**Is your feature request related to a problem? Please describe.**
For better control over deployment, it would be nice to be able to define some thresholds as supported natively via
DeploymentConfiguration.

**Describe the solution you'd like**
```
services:
  serviceA:
    deploy:
      update_config:
        parallelism: N
        max_failure_ratio: F
```
**Describe alternatives you've considered**
If update_config not specified, and `x-aws-min_percent` or `x-aws-max_percent` are defined at the service level,
set the properties accordingly.
