### ISSUE TITLE
service level x-alarms with pre-defined alarms

### ISSUE THREAD

**Issue by JohnPreston** [compose-x/ecs_composex#429]
**Is your feature request related to a problem? Please describe.**
As as developer or cloud engineer, I want to monitor and raise alarms when my services have some issue.
There is a regular set of alarms that I would like to be able to declare and Compose-X would automatically configure these for me.

**Describe the solution you'd like**
```yaml
services:
  serviceA:
    deploy:
      x-alarms:
        PreDefined:
          - HighCpuUsageAndMaxScaled: # Composite alarm, CPU is maxed out and current count == max scaling count
          - HighLogsVolume # Alarm if the service tasks produce a lot of logging
          - HighRetryCount: # Alarm that compares PendingCount and RunningCount to detect service anomaly in stabilizing
        alarm-01:
          Properties: {} # Follows the normal x-alarm behaviour, automatically uses the ECS service as dimension
```

**Describe alternatives you've considered**

**Additional context**
[Composite Alarms
](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-cloudwatch-compositealarm.html)
