### ISSUE TITLE
x-alarms - support for composite alarms

### ISSUE THREAD

**Issue by JohnPreston** [compose-x/ecs_composex#430]
**Is your feature request related to a problem? Please describe.**
I defined a set of alarms which I would like to use in a composite alarm.
Therefore when I declare an alarm I would like to link logically the ones already defined. For the actions, follow the same logic as x-alarms to enable service scaling or SNS topics.

**Describe the solution you'd like**
```yaml
x-alarms:
  a-first-alarm:
    Properties: {}
  a-second-alarm:
    Properties: {}
  composite-alarm:
    Properties:
      ActionsEnabled: Boolean
      AlarmDescription: String
      AlarmName: String
      AlarmRule: ALARM(a-first-alarm) AND ALARM(a-second-alarm)
    Services: []
    Topics: []
```

**Describe alternatives you've considered**

**Additional context**
[Composite Alarm
](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-cloudwatch-compositealarm.html)
