### ISSUE TITLE
DeleteDefaultService broken in 0.13.x

### ISSUE THREAD

**Issue by jackqu7** [compose-x/ecs_composex#435]
**Describe the bug**
An x-event with DeleteDefaultService has no effect in 0.13.x - a service will still be created.

The issue is caused by the default scaling target created in https://github.com/compose-x/ecs_composex/blob/9fbe3aaec30276c1dee57c7ebcb1a1f3d8e1192d/ecs_composex/ecs/ecs_service.py#L258
this conflicts with the check in https://github.com/compose-x/ecs_composex/blob/9fbe3aaec30276c1dee57c7ebcb1a1f3d8e1192d/ecs_composex/events/events_ecs.py#L193

**To Reproduce**
```
job:
  ...

x-events:
  job:
    Properties:
      Description: "nightly job"
      ScheduleExpression: "cron(0 0 * * ? *)"
    Services:
      - name: job
        TaskCount: 1
        DeleteDefaultService: True
```
**Expected behavior**
Service not created - scheduled task only.
