### ISSUE TITLE
FR - x-ecs run command IAM support

### ISSUE THREAD

**Issue by JohnPreston** [compose-x/ecs_composex#451]
**Is your feature request related to a problem? Please describe.**
I want to run ECS commands with the new feature. I would like IAM permissions to be automated

**Describe the solution you'd like**
```yaml
services:
  abcd:
    x-iam:
      EnableEcsCommand: True
```

**Describe alternatives you've considered**
```yaml
services:
  abcd:
    x-ecs:
      EnableEcsCommand: True
```

**Additional context**
