### ISSUE TITLE
FR: make enabling prometheus metrics collection easy

### ISSUE THREAD

**Issue by JohnPreston** [compose-x/ecs_composex#453]
**Is your feature request related to a problem? Please describe.**
As a developer or operational team, we want to collect metrics in Prometheus ECS. Given the amount of configuration that is to be done for this, we would like to have an easy way to enable the feature.

**Describe the solution you'd like**
```yaml
services:
  service-a:
    x-prometheus:
      CollectForAppMesh: True/False
      CollectForJavaJmx: True/False
      CollectForNginx: True/False
      CollectForNginxPlus: True/False
```

**Additional context**
https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/ContainerInsights-Prometheus-Sample-Workloads-ECS.html
