### ISSUE TITLE
Add Code Guru at the top level

### ISSUE THREAD

**Issue by krishin-js** [compose-x/ecs_composex#461]
**Is your feature request related to a problem? Please describe.**
Should I need multiple services to use a single Code Guru Profiler, I would need to create the profiler separately (CFN/Manually) & then apply the name in the ENV files. I would also need to manage the IAM permissions. This seems a bit disjointed and we need a way to do all of this via compose-x.

**Describe the solution you'd like**
In my ENV file, I would like to do something like (pardon indentation issues, if any):

```
x-codeguru-profilers:
  codeguru-for-serviceX:
    <properties & configurations>

services:
  serviceA:
    ...<some configs>...
    x-codeguru-profiler: codeguru-for-serviceX
  serviceB:
    ...<some configs>...
    x-codeguru-profiler: codeguru-for-serviceX
  Randomservice:
    ...<some configs>...
    x-codeguru-profiler: True
```

In this case, serviceA & serviceB would be in the same profiler group with nothing else required to be done; but Randomservice would have a profiler of it's own (as already supported).

**Comment by JohnPreston** [comment]
```yaml
x-codeguru_profiler:
  Profile01:
    Properties: {}
    Services:
      - name: serviceA
        access: RW
```

**Comment by krishin-js** [comment]
Looking to test this out on the main branch (since the feature branch seems to be deleted after code merge) - Unfortunately, I get the following error:

> KeyError: ('Only valid keys for a service definition are', ['build', 'cap_add', 'cap_drop', 'cgroup_parent', 'command', 'configs', 'container_name', 'credential_spec', 'depends_on', 'deploy', 'devices', 'dns', 'dns_search', 'entrypoint', 'env_file', 'environment', 'expose', 'external_links', 'extra_hosts', 'healthcheck', 'hostname', 'image', 'init', 'isolation', 'labels', 'labels', 'links', 'logging', 'network_mode', 'networks', 'pid', 'ports', 'privileged', 'read_only', 'restart', 'secrets', 'security_opt', 'shm_size', 'stop_signal', 'sysctls', 'tmpfs', 'ulimits', 'user', 'userns_mode', 'volumes', 'x-alarms', 'x-configs', 'x-iam', 'x-logging', 'x-network', 'x-scaling', 'x-xray'], ['x-aws-autoscaling', 'x-aws-logs_retention', 'x-aws-max_percent', 'x-aws-min_percent', 'x-aws-policies', 'x-aws-pull_credentials', 'x-aws-role'], 'Got', ['build', 'deploy', 'environment', 'image', 'networks', 'ports', 'secrets', **'x-codeguru-profiler'**, 'x-iam', 'x-network'])

**Buildspec contains:** pip install ecs_composex>=0.14.1

yaml file:

```
x-codeguru_profiler:
  projectA-services-profiler:
    Services:
      - name: service1
        access: RW
      - name: service2
        access: RW

```
