### ISSUE TITLE
S3 bucket Permissions for Deleting an object

### ISSUE THREAD

**Issue by krishin-js** [compose-x/ecs_composex#463]
**Describe the bug**
I'm trying to give an ECS service GetObject*/PutObject*/DeleteObject* access to an S3 bucket using compose-x as shown below. However, when looking at the Task Role in AWS console, it seems to always put default permissions (RW on Object + List Only Bucket).

**To Reproduce**
Use the following in the yaml file (apologies for the indentation issues, if any):

```
x-s3:
  bucket-01:
    Properties:
      <SOME PROPERTIES>
      LifecycleConfiguration:
        <SOME CONFIGS>
      BucketEncryption:
        <SOME CONFIGS>
    MacroParameters:
      <SOME CONFIGS>
    Settings:
      <SOME CONFIGS>
    Services:
      - name: service-01
        access:
          bucket: ListOnly
          objects: RWDelete
```

**Expected behavior**
In the above case, the task role must also include DeleteObject*

**Desktop (please complete the following information):**
 Used the latest version of compose-x

**Comment by JohnPreston** [comment]
Use the `CRUD` policy. Policies available are in the s3.perms.json or you can use the [AWS SAM Policies for S3](https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-policy-template-list.html#s3-read-policy)

**Comment by krishin-js** [comment]
Unfortunately, even after using CRUD, the output is still the same. I've tried:

```
Services:
  - name: service-01
    access:
      bucket: ListOnly
      objects: CRUD
```

From the [documentation](https://docs.compose-x.io/syntax/compose_x/s3.html), I'm not sure I fully understand (which seems to be the crucial bit):
"If you indicate a string, the default permissions (bucket: ListOnly and objects: RW) will be applied."
 
Sorry, but I can't seem to figure out what am I missing.
