### ISSUE TITLE
Add look-ups for Code-Guru Profiler

### ISSUE THREAD

**Issue by krishin-js** [compose-x/ecs_composex#465]
**Is your feature request related to a problem? Please describe.**
When using Code-Guru Profiler, I would like to be able to use look-ups, where it could be possible to use an existing profiler for services within a repo.

**Describe the solution you'd like**
```
x-codeguru_profiler:
  profilerA:
    Properties: {}
    Services:
      - name: serviceA
        access: RW
    Lookup:
      Tags:
        - ...
        - ...
```
