### ISSUE TITLE
FR: x-ecr for services

### ISSUE THREAD

**Issue by JohnPreston** [compose-x/ecs_composex#477]
As a developer I publish the docker images into AWS ECR.
I would like to be able to leverage AWS APIs to identify a few things and set some options with regard to pre-deployments validation.

```yaml
services:
  serviceA:
    image: registry/image:tag
    x-ecr:
      Registry: registry to use # Optional
      RepositoryName: <name of the repository>
      VulnerabilitiesScan:
        Fail: True|False # Whether compose-x should report !0 if the security findings are above threshold
        TreatFailedAs: Success || Failure # If the scan of the image state is failed, whether exec should fail or not.
        Thresholds:
          CRITICAL: 0
          HIGH: 0
          MEDIUM: 0
          LOW: 0

```
