### ISSUE TITLE
x-ecr.Interpolate SHA

### ISSUE THREAD

**Issue by JohnPreston** [compose-x/ecs_composex#481]
As a developer, I want to use the SHA of the image that I have in AWS ECR.

```yaml

services:
  serviceA:
    image: image_in_ecr
    x-ecr:
      InterpolateWithDigest: True|False

```
