### ISSUE TITLE
Enforce S3 Buckets to require requests to use HTTPS

### ISSUE THREAD

**Issue by krishin-js** [compose-x/ecs_composex#490]
**Is your feature request related to a problem? Please describe.**
Given I have used Compose-x for creation of s3 buckets
Then I have no option to enforce requests over only HTTPS

**Describe the solution you'd like**
According to AWS Security Best Practices, S3 buckets should have policies that require all requests (Action: S3:*) to only accept requests over HTTPS. Therefore, we could enforce requests over HTTPS either by default by adding a suitable bucket policy AND/OR provide an option where this could be enabled.

** Alternative **
An alternative would be to allow us to specify bucket policies for the s3 buckets

**Comment by krishin-js** [comment]
Hi @JohnPreston  - Thanks for your quick response. I can completely understand if bucket policies part would work only for s3 buckets created by compose-x and not for look-ups. I would be happy with the first option:

```
x-s3:
  new-bucket:
    MacroParameters:
      BucketPolicy:
         Statement: [{IAM statement, bucket name auto defined}]
         EnforceSecureConnection: bool

```

Giving us the option to manage bucket policies (not only for enforcing secure connection but for other use-cases too) for s3 buckets created by compose-x would help a great deal to keep all our s3 configs and policies in one place along with the rest of our services.

**Comment by JohnPreston** [comment]
Added bucket level access predefined IAM policy to add the deny on the IAM role.

**Comment by JohnPreston** [comment]
For lookup bucket
```yaml
        - PolicyDocument:
            Statement:
              - Action: s3:*
                Condition:
                  Bool:
                    aws:SecureTransport: 'false'
                Effect: Deny
                Resource:
                  - !Sub
                    - ${BucketArn}
                    - BucketArn: !FindInMap
                        - s3
                        - bucket08
                        - Arn
                  - !Sub
                    - ${BucketArn}/*
                    - BucketArn: !FindInMap
                        - s3
                        - bucket08
                        - Arn
                Sid: !Sub 's3-bucket-ssl-requests-onlyToSslBucketObjefsAccessbucket08'
            Version: '2012-10-17'
          PolicyName: !Sub 's3-bucket-ssl-requests-onlySslBucketObjefsAccessbucket08${RootStackName}'
```
and for new bucket
```yaml
        - PolicyDocument:
            Statement:
              - Action: s3:*
                Condition:
                  Bool:
                    aws:SecureTransport: 'false'
                Effect: Deny
                Resource:
                  - !Ref 'bucket01BucketArn'
                  - !Sub
                    - ${BucketArn}/*
                    - BucketArn: !Ref 'bucket01BucketArn'
                Sid: !Sub 's3-bucket-ssl-requests-onlyToSslBucketObjefsAccessbucket01'
            Version: '2012-10-17'
          PolicyName: !Sub 's3-bucket-ssl-requests-onlySslBucketObjefsAccessbucket01${RootStackName}'
```
