### ISSUE TITLE
[FR] AWS ElasticSearch/OpenSearch support

### ISSUE THREAD

**Issue by JohnPreston** [compose-x/ecs_composex#541]
As a developer I might need to create a new / connect to an existing OpenSearch deployment.

```yaml
x-opensearch:
  domain01:
    Properties: {}
    MacroParameters: {}
    Lookup: {}
    Settings: {}
    Services: []
```

Allow to set the VPC Subnets to auto-populate the `VPCOptions`

**Additional context**
https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-opensearchservice-domain.html
