### ISSUE TITLE
[FR] Allow to set more Prometheus scraping configuration for services.x-prometheus

### ISSUE THREAD

**Issue by JohnPreston** [compose-x/ecs_composex#551]
Given that I have metrics to collect
And metrics might be available more regularly than every 60 seconds (value set today)
Then I would like to be able to change the scraping configuration.

```yaml

ScrapingConfiguration:
  Interval: <duration>
  Timeout: <duration>
```

alternatively, could have 

```yaml

ScrapingConfiguration:
  ScrapingConfigurationFile: <str> # Path to a scraping configuration file
```
