### ISSUE TITLE
[FR] x-rds / x-docdb / x-opensearch / x-elasticache - provide IAM access support

### ISSUE THREAD

**Issue by JohnPreston** [compose-x/ecs_composex#569]
**Is your feature request related to a problem? Please describe.**
As a developer, I would like the ability in my ECS Service to perform API calls to possibly describe my DB Clusters attributes and other associated resources. Currently the only access provided is to the secret that contains endpoints, but that might not be enough.

Therefore we would like the ability in `x-<rds|doccb|etc>.services.access` to use some IAM policies to describe the resources.

**Describe the solution you'd like**
```yaml
x-rds:
  dbA:
    Properties: {}
    Services:
    - name: app01
      access:
        iam: Describe
```
