### ISSUE TITLE
[FR] services.x-logging add Subscription Filter to x-kinesis or x-kinesis_firehose

### ISSUE THREAD

**Issue by JohnPreston** [compose-x/ecs_composex#604]
As a user, I might want to funnel log groups to x-kinesis and/or x-kinesis_firehose 

**Describe the solution you'd like**
```yaml
services:
  myapp-to-log:
    x-logging:
      SubscriptionFilters:
        - FilterPattern: "*"
          DestinationArn: x-kinesis::stream-01
        - FilterPattern: "{$.userIdentity.type = Root}"
          DestinationArn: x-kinesis_firehose::stream-01
          
x-kinesis:
  stream-01:
    Properties: {}
x-kinesis_firehose:
  stream-01:
    Properties: {}
```

Each element in `SubscriptionFilters` would allow for original properties.
By default, the IAM Role for cloudwatch will be re-created and permissions set accordingly.
