### ISSUE TITLE
[FR] Set return values directly in services `environment`

### ISSUE THREAD

**Issue by JohnPreston** [compose-x/ecs_composex#605]
As a user I currently have to set the `ReturnValues` at the `Services` level for a given resource, such as

```yaml
services:
  my-service: {}

x-s3:
  bucket:
    Services:
      my-service:
        Access: {}
        ReturnValues:
          BucketName: MY_SUPER_BUCKET
```
I would like to be able to do something simpler, as follows

```yaml
x-s3:
  bucket: {}

services:
  my-service:
    environment:
      MY_SUPER_BUCKET: x-s3::bucket::BucketName
```

We get a 3 parts value

`x-<module>`::<resource_name>::<ReturnValue>`

ECS Compose-X would automatically set the env-var appropriately.

In case of conflict, for a same env var key (i.e here `MY_SUPER_BUCKET`), the value set from `services.environment` should takes precedence?
