### ISSUE TITLE
[FR] x-elbv2.MacroParameters x-s3 logging

### ISSUE THREAD

**Issue by JohnPreston** [compose-x/ecs_composex#612]
As a elbv2 user, I'd like to get the LB logs shipped into AWS S3.
Given that with ECS Comose-X I can create both things, with x-elbv2 and x-s3, I'd like to be able to define a one-liner that will auto-configure logging from ELB to S3 automatically

```yaml
x-s3:
  logging-bucket: {}

x-elbv2:
  publicLB:
    MacroParameters:
      S3Logging: x-s3::logging-bucket
```
