### ISSUE TITLE
[FR] x-dashboards to add `Alarms`

### ISSUE THREAD

**Issue by JohnPreston** [compose-x/ecs_composex#613]
Using x-alarms and x-dashboards, I'd like to be able to define which alarms I'd like to see the status along the service metrics

```yaml

x-alarms:
  cpu-alarm: {}

x-dashboards:
  my-main-dashboard:
    Services: {}
    Alarms:
      - x-alarm: cpu-alarm
      - AlarmName: an-existing-alarm-in-account
```
