### ISSUE TITLE
[FR] x-dynaomdb.`Scaling`

### ISSUE THREAD

**Issue by JohnPreston** [compose-x/ecs_composex#614]
As a heavy dynamodb user, I want to define autoscaling for a given DynamoDB (and possibly its indexes)

```
x-dynamodb:
  tableA:
    Scaling:
      Table:
        WriteCapacityUnits:
          MinCapacity: xx
          MaxCapacity: xx
          UtilizationTarget: 60.0 # Reads 60.0%
        ReadCapacityUnits:
          MinCapacity: xx
          MaxCapacity: xx
          UtilizationTarget: 60.0 # Reads 60.0%
      Indexes:
        <index_name>:
          WriteCapacityUnits: {}
          ReadCapacityUnits: {}
```
