### ISSUE TITLE
[FR] x-<resource>::<name>::Property in container command

### ISSUE THREAD

**Issue by JohnPreston** [compose-x/ecs_composex#618]
As a user who might want to update the command for containers, I'd like to able to retrieve a resource property and insert that in the command line.
For example, if I needed the bucket arn

```yaml
x-s3:
  MyBucket: {}

services:
  serviceA:
    command:
      - --from-s3
      - x-s3::MyBucket:Arn
```
This is similar to how the values in `environment` get replaced, but for the command of the service.
