### ISSUE TITLE
[FR] FireLens - add support for extra parser files

### ISSUE THREAD

**Issue by JohnPreston** [compose-x/ecs_composex#626]
Currently, in Advanced, I can add `SourceFile` which allow me to add filters etc, which will be included to the final configuration that FireLens will generate.

But if I have custom Parser, I need to set a ParserFile property pointing to it, and cannot have it as part of the main configuration file.
Therefore, I'd like to have

```
x-logging:
  FireLens:
    Advanced:
      SourceFile: <>
      ParserFiles:
        - /path/to/parser
```

`ParserFiles` would be a list of files to add to the shared docker volume and add to the general [SERVICE] instruction.
