### ISSUE TITLE
[FR] `secrets` should be available to both task and exec roles by default

### ISSUE THREAD

**Issue by JohnPreston** [compose-x/ecs_composex#635]
It'd make more sense to make the secret available to both the task and execution role by default for "ease of use" and let the user restrict which roles should have access with `LinksTo` when they want to improve security further.

**Comment by JohnPreston** [comment]
On top of that, in `x-secret`, allow to give a custom env var name

```yaml

secrets:
  my_secret:
    x-secret:
      Name: /some/secret
      VarName: MY_VERY_SECRET
```

The value for `MY_VERY_SECRET` would be the secret `Name` or the secret ARN (favor the ARN)
