### ISSUE TITLE
[FR] services.x-logging.LogFilters

### ISSUE THREAD

**Issue by JohnPreston** [compose-x/ecs_composex#638]
When using AWS CloudWatch (possibly support FireLens + cloudwatch) I would like an easy way to create metrics filters.

https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-logs-metricfilter.html

```yaml
services:
  my-app:
    x-logging:
      LogFilters:
        Filters: [AWS::Logs::MetricFilter]
```
CW Names will be auto-generated for these.
