### ISSUE TITLE
[FR] x-s3.NotificationConfiguration and x-sqs support

### ISSUE THREAD

**Issue by JohnPreston** [compose-x/ecs_composex#639]
As an AWS S3 and SQS user, I would like to use [QueueNotification](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-s3-bucket-notificationconfig-queueconfig.html) and point to x-sqs queues defined. Compose-X will automatically create a new Queue Policy allowing the S3 service to publish to SQS.

```yaml
x-sqs:
  s3-notifications:
    Properties: {}

x-s3:
  Bucket:
    Properties:
      NotificationConfiguration:
        QueueConfigurations:
          - Queue: x-sqs::s3-notifications
            Event: ""
            Filter: {}

```

This however only works for new queues as existing queues might have policies already set.
