### ISSUE TITLE
[BUG] Kinesis on-demand is not supported

### ISSUE THREAD

**Issue by smazurov** [compose-x/ecs_composex#677]
**Describe the bug**
When working with on-demand kinesis streams, it seems things are failing to properly be looked up or created.

**To Reproduce**

Simple Yaml:
```yaml
x-kinesis:
  streamA:
    Properties:
      Name: streamA
      StreamModeDetails: 
        StreamMode: ON_DEMAND
    # Lookup:
    #   Tags:
    #     - Name: existingStreamA
    Services:
        serviceA:
          Access: Consumer
```

Generates the warning:
```
2023-07-17 10:13:43 [ WARNING] ShardCount must be set. Defaulting to 1
```
CF then fails:
```
Resource handler returned message: "ShardCount is not expected when StreamMode=ON_DEMAND" (HandlerErrorCode: InvalidRequest)
```

Additionally, lookup of an existing On Demand stream fails:
```
2023-07-17 10:01:29 [    INFO] x-kinesis.existingStreamA - Lookup via Tags
2023-07-17 10:01:30 [    INFO] x-kinesis.existingStreamA - Matched to <arn here>
Traceback (most recent call last):
  File "/home/stepan/.local/bin/ecs-compose-x", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/stepan/.local/lib/python3.11/site-packages/ecs_composex/cli.py", line 206, in main
    root_stack = generate_full_template(settings)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/stepan/.local/lib/python3.11/site-packages/ecs_composex/ecs_composex.py", line 256, in generate_full_template
    add_x_resources(settings)
  File "/home/stepan/.local/lib/python3.11/site-packages/ecs_composex/ecs_composex.py", line 180, in add_x_resources
    x_stack = module.stack_class(
              ^^^^^^^^^^^^^^^^^^^
  File "/home/stepan/.local/lib/python3.11/site-packages/ecs_composex/kinesis/kinesis_stack.py", line 154, in __init__
    resolve_lookup(module.lookup_resources, settings, module)
  File "/home/stepan/.local/lib/python3.11/site-packages/ecs_composex/kinesis/kinesis_stack.py", line 140, in resolve_lookup
    settings.mappings[module.res_key].update(
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
KeyError: 'x-kinesis'

```
**Expected behavior**
On Demand streams should be supported. If this is a feature request then feel free to re-classify.

**Desktop (please complete the following information):**
 - OS: Fedora
 - Python version: 3.11
 - 0.23.16

**Comment by JohnPreston** [comment]
Thanks @smazurov for reporting this.
Give me a few minutes to give you a branch to fix the lookup.
Then I will patch so that if `StreamMode: ON_DEMAND` is set that the `ShardCount` is dropped/set to `AWS::NoValue`

**Comment by JohnPreston** [comment]
Yeah, that's actually my own fault, tried to bee too smart.
```python
    if not keyisset("ShardCount", stream.properties):
        LOG.warning("ShardCount must be set. Defaulting to 1")
        props["ShardCount"] = 1
```

**Comment by smazurov** [comment]
ideally this works with existing streams as they're created outside of ecs.

**Comment by JohnPreston** [comment]
@smazurov  if you could test locally for me, with both use-cases. See #678 . If you could test locally with
`pip install git+https://github.com/compose-x/ecs_compose@fix/x-kinesis` to confirm that'd be great.
Tested properties "smart" correction with

```yaml
services:
  nothing:
    image: nginx

x-kinesis:
  # LookupStream:
  #   Lookup:
  #     Tags:
  #       - Environment: testing
  #       - Name: lookup-testing
  #   Services:
  #     nothing:
  #       Access: Consumer

  streamA:
    Properties:
      Name: streamA
      StreamModeDetails:
        StreamMode: ON_DEMAND
    # Lookup:
    #   Tags:
    #     - Name: existingStreamA
    Services:
        serviceA:
          Access: Consumer

  streamB:
    Properties:
      Name: streamB
      ShardCount: 1
      StreamModeDetails:
        StreamMode: ON_DEMAND
    # Lookup:
    #   Tags:
    #     - Name: existingStreamA
    Services:
        serviceA:
          Access: Consumer

  streamC:
    Properties:
      Name: streamC
      ShardCount: 1
      StreamModeDetails:
        StreamMode: PROVISIONED
    # Lookup:
    #   Tags:
    #     - Name: existingStreamA
    Services:
        serviceA:
          Access: Consumer

  streamD:
    Properties:
      Name: streamD
      StreamModeDetails:
        StreamMode: PROVISIONED
    # Lookup:
    #   Tags:
    #     - Name: existingStreamA
    Services:
        serviceA:
          Access: Consumer

```

**Comment by smazurov** [comment]
Not sure anyone would do this, but I had:
```yaml
    Properties:
      ShardCount: 0
      Name: streamA
      StreamModeDetails: 
        StreamMode: ON_DEMAND
```

It let me create the CF, then failed once in there.

As intended, though, it works great 👍🏻 for both new and existing streams. 

--------

Unrelated: the `Consumer` role seems too limited

```
Failed to connect to aws_kinesis: AccessDeniedException: User: <arn> is not authorized to perform: kinesis:DescribeStream on resource: <stream arn> because no identity-based policy allows the kinesis:DescribeStream action
```
and I am not sure how to extend `Consumer` role. I can create an `x-iam` Policy on the service definition, but how would I reference the resource value of newly created kinesis stream? This goes beyond Kinesis, as a lot of kinesis implementations use dynamodb to do checkpoint tracking, so some level of extending seems necessary.  Not a blocker/relevant to this bug, though.

**Comment by JohnPreston** [comment]
Oh okay. I tested with very basic code so it might not have covered everything.
I never came around to allowing creating custom roles. If you have a list of actions you know you need and change the actions list.
However how come it requires dynamos API calls?

**Comment by smazurov** [comment]
Kinesis uses dynamo for checkpointing. It might be OK to create that manually, but [heres](https://docs.aws.amazon.com/streams/latest/dev/tutorial-stock-data-kplkcl-iam.html) a good example of "minimum permissions"

**Comment by JohnPreston** [comment]
> Kinesis uses dynamo for checkpointing. It might be OK to create that manually, but [heres](https://docs.aws.amazon.com/streams/latest/dev/tutorial-stock-data-kplkcl-iam.html) a good example of "minimum permissions"
> 
> > Note: their docs are slightly off, `SubscribeToShard`, ` RegisterStreamConsumer` should be Consumer permissions, not producer (afaik)

Thanks for all that, I am updating the kinesis actions now.
I imagine that using KCL you would be specifying the dynamodb table you want to use, right?
I hadn't tested with KCL because - at least at the time, not that I can remember - that was not something supported for python.

I will read up on the docs, but any inights you can offer would be great.

If Indeed as I imagine you are in control of the dynamodb table to use, `x-dynamodb` would be the best way to grant your application permissions.
I will create at `KinesisKCL` permissions profile with the permissions you linked up in there.
If KCL wants to create tables itself, I will have to get creative about adding pre-defined permissions for it via Kinesis.

**Comment by JohnPreston** [comment]
Hey
I like to use JSON Schema for input validation and documentation ;).
What do you think of these "MacroParameters" which are shortcuts to make some things easier.

See https://github.com/compose-x/ecs_composex/blob/c587c6e0dd798a31d4bc5db0a4ed02ac7aec190c/ecs_composex/kinesis/x-kinesis.spec.json

Please feel free to make suggestions.

**Comment by smazurov** [comment]
> I imagine that using KCL you would be specifying the dynamodb table you want to use, right?

From what I see, its pretty standard to let consumer create the table if it doesn't exist. They do also give you an option to use existing table

**Comment by JohnPreston** [comment]
> 

Yes, the table names could be `[*]` but then might as well not bother and just turn the other option on, that will do the same.
It would give the exact same thing as doing
```yaml
services:
  consumer:
    x-iam:
      Policies:
        - PolicyName: DynamoDBAccess
          PolicyDocument:
            Statement:
              - Effect: Allow
                Action: [dynamodb:*]
                Resource: [*]
```
So doesn't make much difference I suppose.
Is the branch with the suggested fix working for you though atm with Lookup etc?
