### ISSUE TITLE
[FR] environment variables as stack parameters

### ISSUE THREAD

**Issue by JohnPreston** [compose-x/ecs_composex#680]
Some environment variables might be useful to have as parameters to the CFN stack of a given service to make it easy to re-use the existing template and avoid changing/re-generating the template each time.

Suggestions

```yaml
services:
  serviceA:
    environment:
      first_var: value1
      second_var: value2
    x-environment:
      SetAsParameter:
```

SetAsParameter would either be a list of the keys to swap as parameters
```yaml
SetAsParameter:
  - second_var
```
or allows the user to set the full CFN definition of parameter
```yaml
SetAsParameter:
  second_var:
    Type: String
    <<: * CFN Parameters Properties
```

These parameters would be created at the very end of the service template creation to ensure that every other parameter has been set, for CFN resources.
With a limit of 200 parameters per stack, if there already were too many parameters, the ones set would come in order as defined in the definition. For example, if there was only 1 parameter available left on the stack, `first_var` would be set, leaving `second_var` out
