### ISSUE TITLE
[BUG] elbv2 with empty DefaultActions crashes on target with Conditions

### ISSUE THREAD

**Issue by thorfi** [compose-x/ecs_composex#696]
**elbv2 with empty DefaultActions crashes on target with Conditions**

**To Reproduce**
1. How you installed ECS ComposeX (via pip install)
2. How you are executing it ? (as a cli tool)
3. Docker compose chunk:
```
x-elbv2: # ecscomposex
  application-elb:
    Properties:
      Scheme: internet-facing
      Type: application
      LoadBalancerAttributes:
        idle_timeout.timeout_seconds: "4000"
        routing.http.drop_invalid_header_fields.enabled: "true"
    MacroParameters:
      cross_zone: true
      desync_mitigation_mode: defensive
      Ingress:
        ExtSources:
          - IPv4: "0.0.0.0/0"
            Description: ANY
    DnsAliases:
      - Route53Zone: x-route53::public-zone
        Names:
          - "*.example.com"
          - "example.com"
    Services:
      - name: foo:foo
        port: 3680
    Listeners:
      - Port: 80
        Protocol: HTTP
        Certificates: [ ] # We explicitly don't have any
        DefaultActions:
          - Redirect: HTTP_TO_HTTPS
        Targets: [ ] # We explicitly don't have any
      - Port: 443
        Protocol: HTTPS
        Certificates:
          - CertificateArn: "...."
          - x-acm: public-cert
        DefaultActions: []
        Targets:
          - name: spindle:spindle
            Conditions:
            - Field: host-header
              HostHeaderConfig:
                Values:
                  - "example.com"
                  - "*?.example.com"
                  - "help.example.com"
```

4. Crash here:
```
ecs_composex/elbv2/elbv2_stack/helpers.py", line 402, in handle_non_default_services
    if isinstance(service_def["access"], str) and service_def["access"] == "/":
                  ~~~~~~~~~~~^^^^^^^^^^
KeyError: 'access'
```

**Expected behavior**
This should not crash on the missing access clause work and fall through to returning "I'm a teapot".

**Logs**
N/A.

**Desktop:**
 - OS: macOS 14.1 (Sonoma)
 - Python version (3.10)
