### ISSUE TITLE
[BUG] Ingress.AwsSources.SecurityGroup `AccountOwner` not working

### ISSUE THREAD

**Issue by JohnPreston** [compose-x/ecs_composex#700]
```yaml
    x-network:
      Ingress:
        AwsSources:
          - Id: sg-ABCD
            Type: SecurityGroup
            AccountOwner: "00011100000000"
```
The AccountOwner is being replacted by `AWS::AccountId`
