### ISSUE TITLE
[BUG] x-cloud: should generate Vpc: Ref: VpcID

### ISSUE THREAD

**Issue by thorfi** [compose-x/ecs_composex#704]
**Bug**
When using x-cloud: with a private namespace, the resulting Resources: entry generated contains `Vpc: x-vpc:VpcId`

It should use `Vpc: Ref: VpcId` instead.

****
1. pip install
2. cli tool
3. Docker compose file
```
x-cloudmap: # ecscomposex
  PrivateZone:
    ZoneName: foo.local
```
4. Results in:
```
Resources:
  PrivateZone:
    Properties:
      Name: foo.local
      Tags:
        - Key: CreatedByComposeX
          Value: true
        - Key: compose-x:version
          Value: 0.23.27-rc0
      Vpc: x-vpc:VpcId
    Type: AWS::ServiceDiscovery::PrivateDnsNamespace
```

**Expected behavior**
```
Resources:
  PrivateZone:
    Properties:
      Name: foo.local
      Tags:
        - Key: CreatedByComposeX
          Value: true
        - Key: compose-x:version
          Value: 0.23.27-rc0
      Vpc:
        Ref: VpcId
    Type: AWS::ServiceDiscovery::PrivateDnsNamespace
```

**Logs**
Not applicable

**Desktop (please complete the following information):**
 - OS: macOS 14.1 (Sonoma)
 - Python version: 3.10

**Comment by JohnPreston** [comment]
Hi @thorfi 
Thanks for reporting this. If the resolution of `x-vpc::VpcID` is not working then I need to look into that.
There is a post-processing function that would make the modules go over properties of any resource and replace the value with the right thing.

Have you checked whether this works both when you create and lookup the VPC by any chance?

**Comment by JohnPreston** [comment]
I have tested with the following (creates the VPC)

```yaml
x-cloudmap: # ecscomposex
  PrivateZone:
    ZoneName: foo.local
```

And I get
```yaml
Resources:
  PrivateZone:
    Properties:
      Name: foo.local
      Tags:
        - Key: CreatedByComposeX
          Value: true
        - Key: compose-x:version
          Value: 0.23.27-rc2
      Vpc:
        Ref: VpcId
    Type: AWS::ServiceDiscovery::PrivateDnsNamespace
```
However, I do see the bug when using `x-vpc.Lookup`
Can you just confirm for me that you are getting that error when doing `x-vpc.Lookup` please?
