### ISSUE TITLE
[BUG] service.deploy.labels: ecs.ephemeral.storage not working

### ISSUE THREAD

**Issue by thorfi** [compose-x/ecs_composex#719]
#### Bug

service.deploy.labels: ecs.ephemeral.storage does not result in the correct TaskDefinition.EphemeralStorage.SizeInGiB

#### Steps to reproduce the behavior:
1. pip install
2. cli
3. Docker compose file
```
services:
  foo:
    deploy:
      labels:
        ecs.ephemeral.storage: 200
```
4. Output CloudFormation file `foo.yaml`
```
  EcsTaskDefinition:
    Properties:
      ...
      EphemeralStorage:
        Ref: AWS::NoValue
      ...
    Type: AWS::ECS::TaskDefinition
```
        
**Expected behavior**

Output CloudFormation file `foo.yaml`
```
  EcsTaskDefinition:
    Properties:
      ...
      EphemeralStorage:
        Fn::If:
          - UseFargate
          - SizeInGiB: 200
          - Ref: AWS::NoValue
      ...
    Type: AWS::ECS::TaskDefinition
```

#### Logs
N/A

#### Desktop
 - OS: macOS 14.1 (Sonoma)
 - Python 3.12
 - ecs-composex [v0.24.1](https://github.com/compose-x/ecs_composex/releases/tag/v0.24.1)
