### ISSUE TITLE
[FR] x-s3_upload to upload files to S3 buckets

### ISSUE THREAD

**Issue by JohnPreston** [compose-x/ecs_composex#725]
It'd be useful to have compose-x potentially synchronize or upload files to S3.
If source file not found or any error, skip

```yaml
x-s3_upload:
  files:
    path_to_source_file:
      bucket_name: <>
      key: <>
```
