### ISSUE TITLE
Stuck at the error on aws - The closest matching container-instance is missing an attribute required by your task.

### ISSUE THREAD

**Issue by chughrahul** [compose-x/ecs_composex#731]
My docker compose file - 
```
version: '3.8'
x-cluster:
  Lookup: Rahul-Backend-Staging
x-vpc:
  Lookup:
    VpcId:
      Tags:
        - Name: Rahul-Backend-VPC
    PublicSubnets:
      Tags:
        - Name: public-Rahul-Backend-1
    AppSubnets:
      Tags:
        - Name: private-Rahul-Backend-1
    StorageSubnets:
      Tags:
        - Name: private-Rahul-Backend-1
services:
  app:
    deploy:
      labels:
        ecs.task.family: Test-Image
        ecs.compute.platform: EC2
      resources:
        reservations:
          cpus: "0.25"
          memory: 1GB
    logging:
      driver: awslogs
      options:
        awslogs-group: awslogs-Rahul-Test-Image
        awslogs-create-group: "false"
    build:
      context: ./
      dockerfile: Dockerfile
    image: ${AWS_REGISTRY}/test:TestImage_${IMAGE_TAG}
    networks:
      default: null
```

I'm using the command ```ecs-compose-x up -n test -f docker-compose.yml```.
It is able to push to a cloudformation and made service in cluster. However immediately after that service is giving error - 
```
service [test2-*] was unable to place a task because no container instance met all of its requirements. 
The closest matching container-instance [<>] is missing an attribute required by your task. 
For more information, see the Troubleshooting section of the Amazon ECS Developer Guide.
```
