### ISSUE TITLE
[FR] Use/lookup for load balancer

### ISSUE THREAD

**Issue by zahornyak** [compose-x/ecs_composex#746]
**Is your feature request related to a problem? Please describe.**
Currently, I want to use existing load balancer for my preset, but I cannot do that or there are no docs that I can do that

**Describe the solution you'd like**
I would like to have possibility to use use/lookup for x-elbv2

**Describe alternatives you've considered**
didnt find any

**Comment by JohnPreston** [comment]
hello @zahornyak 
That is a complete docs oversight on my end, `x-elbv2.Lookup` is available in version 1.x
Let me make sure to have this documented.

**Comment by zahornyak** [comment]
@JohnPreston you're right. But how to use that? When I use it like that:
```
x-elbv2:
  lookup:
    loadbalancer:
      Tags:
        - Name: test-balancer
```
it does not work

I have errors like that:
`jsonschema.exceptions.ValidationError: {'loadbalancer': {'Tags': [{'Name': 'test'}]}} is not valid under any of the given schemas`

**Comment by JohnPreston** [comment]
So, the error here is just telling you that the Lookup format is incorrect.
God knows why I originally had `Tags: List[{key: value}]` instead of just `Tags: {key: value}`
You can always double check with the JSON schema spec.

```yaml
x-elbv2:
  Lookup:
    loadbalancer:
      Tags:
        Name: test-balancer
```
Should work, on top of my head

**Comment by zahornyak** [comment]
@JohnPreston 
```
x-elbv2:
  Lookup:
    loadbalancer:
      Tags:
        Name: test-balancer
```
didnt work. 
`jsonschema.exceptions.ValidationError: {'loadbalancer': {'Tags': {'Name': 'test-balancer'}}} is not valid under any of the given schemas`

**Comment by JohnPreston** [comment]
@zahornyak what version of compose-x are you using? Latest is 1.0.1, latest nightly is 1.1.0rc1
Also note that the logical name of the LB is missing

```yaml
x-elbv2:
  my-lb-to-lookup-logical-name:
    Lookup:
      loadbalancer:
        Tags:
          Name: test-balancer
```

**Comment by zahornyak** [comment]
Update:
After some time of investigation, I found the required parameters that should exist in the lookup which are 'TargetGroups' or 'Services'

**Comment by JohnPreston** [comment]
> Update: After some time of investigation, I found the required parameters that should exist in the lookup which are 'TargetGroups' or 'Services'

So is it working now? Do you mind if I tag you to review the docs when I open the PR for it?
Feel free to report anything not working :)

**Comment by zahornyak** [comment]
> @zahornyak what version of compose-x are you using? Latest is 1.0.1, latest nightly is 1.1.0rc1 Also note that the logical name of the LB is missing
> 
> ```yaml
> x-elbv2:
>   my-lb-to-lookup-logical-name:
>     Lookup:
>       loadbalancer:
>         Tags:
>           Name: test-balancer
> ```

yeah, I missed that part, but now I've added everything and it works as well. Thank you

**Comment by zahornyak** [comment]
> > Update: After some time of investigation, I found the required parameters that should exist in the lookup which are 'TargetGroups' or 'Services'
> 
> So is it working now? Do you mind if I tag you to review the docs when I open the PR for it? Feel free to report anything not working :)

sure) Thanks

**Comment by zahornyak** [comment]
@JohnPreston I have an additional question regarding load balancer listener rules. As I can see, I can lookup for the listeners but can I lookup for listeners and create listener rules in that listener?
I'm currently doing this:
```yml
x-elbv2:
  lb:
    Lookup:
      loadbalancer:
        Tags:
          Name: test-deleteme
      Listeners:
        1:
          Tags:
            Name: test-deleteme
          Targets:
            - name: all-gateways
              access: test.com


    TargetGroups:
      api:
        Port: 80
        Protocol: TCP
        HealthCheck:
          HealthCheckIntervalSeconds: 17
          HealthCheckProtocol: TCP
          HealthCheckTimeoutSeconds: 10
          HealthyThresholdCount: 2
          UnhealthyThresholdCount: 2
        TargetGroupAttributes:
          deregistration_delay.timeout_seconds: "30"
        Services:
          - Name: web:web
            Port: 80
```
But it does not create any listener rules with a connected target group there.

**Comment by zahornyak** [comment]
@JohnPreston As far as I can see, error `TypeError: string indices must be integers` only exist when I specify:
```yml
          Targets:
            - name: web:api
              Conditions:
                - Field: host-header
                  HostHeaderConfig:
                    Values:
                      - my-domain.tld
```
And I have no idea why it doesn't work. And still interested in how `family:service:8080` formed. I couldn't do the same
