### ISSUE TITLE
[BUG] healthcheck that used to work in 0.24.2 doesn't work in 1.0.1

### ISSUE THREAD

**Issue by rmoesbergen** [compose-x/ecs_composex#748]
I'm getting a ValidationError on a x-elbv2 resource that used to work in 0.24.2, but fails in 1.0.1:

```
jsonschema.exceptions.ValidationError: [{'name': 'portal:portal', 'port': 80, 'protocol': 'HTTP', 'healthcheck': {'HealthCheckPath': '/login', 'HealthCheckIntervalSeconds': 30, 'HealthCheckTimeoutSeconds': 15, 'HealthyThresholdCount': 2, 'UnhealthyThresholdCount': 5, 'Matcher': {'HttpCode': '200-499'}}}] is not of type 'object'

Failed validating 'type' in schema['properties']['Services']:
    {'additionalProperties': False,
     'patternProperties': {'^[a-zA-Z0-9\\:_\\-]+$': {'$ref': '#/definitions/TargetDef'},
                           'x-': {}},
     'type': 'object'}

On instance['Services']:
    [{'healthcheck': {'HealthCheckIntervalSeconds': 30,
                      'HealthCheckPath': '/login',
                      'HealthCheckTimeoutSeconds': 15,
                      'HealthyThresholdCount': 2,
                      'Matcher': {'HttpCode': '200-499'},
                      'UnhealthyThresholdCount': 5},
      'name': 'portal:portal',
      'port': 80,
      'protocol': 'HTTP'}]
```
The docker-compose Yaml looks like this:
```
...
x-elbv2:
  lb:
    Properties:
      Type: application
      Scheme: internet-facing
    MacroParameters:
      timeout_seconds: 600
      desync_mitigation_mode: defensive
      drop_invalid_header_fields: true
      http2: true
      cross_zone: true
      Ingress:
        ExtSources:
          - IPv4: "0.0.0.0/0"
            Description: ANY
    Listeners:
      - Port: 80
        Protocol: HTTP
        DefaultActions:
          - Redirect: HTTP_TO_HTTPS
      - Port: 443
        Protocol: HTTPS
        Certificates:
          - x-acm: mycert
        Targets:
          - name: portal:portal
            access: /
    Services:
      - name: portal:portal
        port: 80
        protocol: HTTP
        healthcheck:
          HealthCheckPath: /login
          HealthCheckIntervalSeconds: 30
          HealthCheckTimeoutSeconds: 15
          HealthyThresholdCount: 2
          UnhealthyThresholdCount: 5
          Matcher:
            HttpCode: 200-499

```
I checked the docs, but don't see the problem. What am I doing wrong?

**To Reproduce**
1. pip install "ecs_composex[ecrscan]==0.24.2"
2. ecs-compose-x up -f docker-compose.yml -p bla --region=eu-central-1 --format=yaml
3. Include the yaml above in a x-elbv2 service

**Expected behavior**
A working ELB with a healthcheck, like in 0.24.2

I suspect this PR has something to do with it: #733

**Comment by JohnPreston** [comment]
Hello @rmoesbergen 
Breaking change of 1.0 is that the services no longer are `list[]` and instead `mappings{}`
Which is what the JSON schema is telling you.
Would you mind trying with the below and let me know?

```yaml
...
x-elbv2:
  lb:
    Properties:
      Type: application
      Scheme: internet-facing
    MacroParameters:
      timeout_seconds: 600
      desync_mitigation_mode: defensive
      drop_invalid_header_fields: true
      http2: true
      cross_zone: true
      Ingress:
        ExtSources:
          - IPv4: "0.0.0.0/0"
            Description: ANY
    Listeners:
      - Port: 80
        Protocol: HTTP
        DefaultActions:
          - Redirect: HTTP_TO_HTTPS
      - Port: 443
        Protocol: HTTPS
        Certificates:
          - x-acm: mycert
        Targets:
          - name: portal:portal
            access: /
    Services:
      name: portal:portal:
        port: 80
        protocol: HTTP
        healthcheck:
          HealthCheckPath: /login
          HealthCheckIntervalSeconds: 30
          HealthCheckTimeoutSeconds: 15
          HealthyThresholdCount: 2
          UnhealthyThresholdCount: 5
          Matcher:
            HttpCode: 200-499

```
