### ISSUE TITLE
Failed to create ECS Task Definition

### ISSUE THREAD

**Issue by tvk134** [compose-x/ecs_composex#755]
The services in my yml file look like this:
```
 flexternal:
    image: [image link]
    deploy:
      labels:
        ecs.task.family: flexternal
    x-ecs:
      CapacityProvideStrategy:
        - CapacityProvider: FARGATE
          Base: 1
          Weight: 1
    build:
      context: (context)
    depends_on:
      - flexiteer
      - mongodb
    ports:
      - "Port numbers"
    environment:
      - MONGO_URL=[URL]
      - FLEXITEER_URL=[URL]

  flexiteer:
    image: [image link]
    deploy:
      labels:
        ecs.task.family: flexternal
    x-ecs:
      CapacityProvideStrategy:
        - CapacityProvider: FARGATE
          Base: 1
          Weight: 1
    build:
      context: (context)
    ports:
      - "Port numbers"
   
 mongodb:
    deploy:
      labels:
        ecs.task.family: mongodb
    image: mongo:latest
    ports:
      - "mongo ports"
    volumes:
      - (volume)
```
When I run the up command, the CLI reports that a stack has been successfully deployed. The stack deployment fails and is rolled back in cloudformation with the error: `Embedded stack was not successfully created: The following resource(s) failed to create: [EcsTaskDefinition]`. This error pops up for mongo when its included and flexternal when mongo isn't included.

Where am I going wrong? What could be causing this? Any help or advice would be great.
