### ISSUE TITLE
[FR] compose - depends_on string format support

### ISSUE THREAD

**Issue by JohnPreston** [compose-x/ecs_composex#756]
In recent compose changes, there is now more details about the depends_on conditions.

```yaml
    depends_on:
      broker:
        condition: service_started
```
The valid list is

* service_started
* service_healthy
* service_completed_successfully

Which aligns very well with the existing deploy.labels `ecs.depends.condition`

If the user sets either, import. If the user sets both, use the `deploy.labels` value as this is clearly the expected behaviour for compose-x to follow.
