### ISSUE TITLE
Add KMS link between resources and newly defined/imported KMS keys

### ISSUE THREAD

**Issue by JohnPreston** [compose-x/ecs_composex#76]
**Is your feature request related to a problem? Please describe.**
I want to use SQS queues with KMS to encrypt the payload.
I should be given the option to use a CMK otherwise use the default key.
When using CMK, the services linked to the queue must be granted decryption access to the queue.

**Describe the solution you'd like**

Using the AWS account KMS key for sqs
```
x-sqs:
  Queue01:
    Properties:
      KmsMasterKeyId: use::alias/aws/sqs
```
**Describe alternatives you've considered**
Alternatively, the following would indicate to create the key with AWS default settings.

```
x-sqs:
  Queue01:
    Properties:
      KmsMasterKeyId: create::sqskey
```
Or to lookup an existing KMS key
```
x-sqs:
  Queue01:
    Properties:
      KmsMasterKeyId: use::sqskey
```

**Comment by JohnPreston** [comment]
Instead of setting that in the properties directly, in order to allow full compatibility with original CFN expectations, this would be a new MacroParameter, generic to all resources supporting specific KMS Key encryption `KmsKey: <key-name>`
If the KMS Key is imported, the value is set via mappings as is for other resources. If the resource is new, via a new parameter to the resource stack.

**Comment by JohnPreston** [comment]
x-kms since allows to do `Lookup` as well as `Use` as for all other resources.

For linking between resources, will allow so by

```yaml
x-kms:
  key-for-sqs:
    Properties: {}

x-sqs:
  Queue01:
    Properties:
      KmsMasterKeyId: x-kms::key-for-sqs
```
Generically, any resource that has an SSE with KMS property will be able to use 

```yaml
MacroParameters:
  EncryptWith: x-kms::key-resource-defined
```

Which will automatically map it to the property of the given resource. This will work for kms keys being created or using lookup/use.
