### ISSUE TITLE
[BUG] Deploys from a public images not working

### ISSUE THREAD

**Issue by AdrKacz** [compose-x/ecs_composex#761]
**Describe the bug**
I ran `ecs-compose-x up -n my-project -f docker-compose.yml`, the stack failed with the following errors:

```
Embedded stack arn:aws:cloudformation:xxx:XXX:stack/xxx-xxx-1234/ABCD was not successfully created: The following resource(s) failed to create: [EcsServiceDefinition].
```

**To Reproduce**
```sh
python3 -m venv venv
source venv/bin/activate
pip install pip -U
pip install ecs-composex
pip install "ecs-composex[ecrscan]"
```

docker-compose.yml
```yml
---
version: '3'
services:
  freqtrade:
    image: org/image:stable
    restart: unless-stopped
    container_name: project
    volumes:
      - "./user_data:/freqtrade/user_data"
    ports:
      - "8080:8080"
    # Default command used when running `docker compose up`
    command: >
      start-script
      --logfile /data/user_data/logs/project.log
```

**Expected behavior**
How can I know what failed in my configuration? It works perfectly fine when running `docker compose up` so I think I'm using an invalid option.

Thank you for your help
