### ISSUE TITLE
[FR] Support for docker image 'tags' property in docker compose build

### ISSUE THREAD

**Issue by raffidahmad** [compose-x/ecs_composex#784]
**Is your feature request related to a problem? Please describe.**
Docker Compose allows specifying multiple tags for an image using the tags property under the build section. However, compose-x currently ignores this property. While it's possible to include tags in the image key, doing so reduces readability and makes the configuration less clean.

**Describe the solution you'd like**
Add support for the tags property in the build section of compose-x. This would allow users to specify multiple tags more cleanly and in alignment with Docker Compose standards. For example:

```
services:
  app:
    build:
      context: .
      tags:
        - my-app:latest
        - my-app:1.0.0
```
