### ISSUE TITLE
[FR] services.x-iam option to pull all the policies into a single managed policy attached to the role.

### ISSUE THREAD

**Issue by JohnPreston** [compose-x/ecs_composex#788]
It might be simpler, from a readability and audit POV to have the policies put together as part of a ManagedPolicy attached to the role, vs having inline policies.

```yaml
services:
  my-app:
    x-iam:
      UseManagedPolicy: bool
```
Would effectively allow to have the policies put in a managed one. Default remains to have inline policies.
