### ISSUE TITLE
[FR] services.x-scaling - Predictive Scaling policy type

### ISSUE THREAD

**Issue by JohnPreston** [compose-x/ecs_composex#789]
Today in ecs-compose-x I can define Step or Target Scaling policies.
With ECS now supporting PredictiveScaling, I would like to be able to create these.

Something to the effect of

```yaml

services:
  my-app:
    x-scaling:
      Range: 0-10
      PredictiveScaling:
        Cpu: x%
        Memory: x%
        CustomMetric:
```
